export const NaritaAirport = {
  NaritaAirport: {
    name: "成田空港",
    rootPath: "/NaritaAirport/",
    networkFile: {
      node: "nrt_node.geojson",
      link: "nrt_link.geojson",
    },
    geoFiles: [
      "NRT1_0_Facility.geojson",
      "NRT1_0_Fixture.geojson",
      "NRT1_0_Floor.geojson",
      "NRT1_0_Space.geojson",
      "NRT1_1_Drawing.geojson",
      "NRT1_1_Facility.geojson",
      "NRT1_1_Fixture.geojson",
      "NRT1_1_Floor.geojson",
      "NRT1_1_Opening.geojson",
      "NRT1_1_Space.geojson",
      "NRT1_2_Drawing.geojson",
      "NRT1_2_Facility.geojson",
      "NRT1_2_Fixture.geojson",
      "NRT1_2_Floor.geojson",
      "NRT1_2_Opening.geojson",
      "NRT1_2_Space.geojson",
      "NRT1_3_Drawing.geojson",
      "NRT1_3_Facility.geojson",
      "NRT1_3_Fixture.geojson",
      "NRT1_3_Floor.geojson",
      "NRT1_3_Opening.geojson",
      "NRT1_3_Space.geojson",
      "NRT1_4_Drawing.geojson",
      "NRT1_4_Facility.geojson",
      "NRT1_4_Fixture.geojson",
      "NRT1_4_Floor.geojson",
      "NRT1_4_Opening.geojson",
      "NRT1_4_Space.geojson",
      "NRT1_4out_Fixture.geojson",
      "NRT1_4out_Floor.geojson",
      "NRT1_4out_Space.geojson",
      "NRT1_5_Drawing.geojson",
      "NRT1_5_Facility.geojson",
      "NRT1_5_Fixture.geojson",
      "NRT1_5_Floor.geojson",
      "NRT1_5_Opening.geojson",
      "NRT1_5_Space.geojson",
      "NRT1_5out_Fixture.geojson",
      "NRT1_5out_Floor.geojson",
      "NRT1_5out_Space.geojson",
      "NRT1_B1_Drawing.geojson",
      "NRT1_B1_Facility.geojson",
      "NRT1_B1_Fixture.geojson",
      "NRT1_B1_Floor.geojson",
      "NRT1_B1_Opening.geojson",
      "NRT1_B1_Space.geojson",
      "NRT2_0_Drawing.geojson",
      "NRT2_0_Facility.geojson",
      "NRT2_0_Fixture.geojson",
      "NRT2_0_Floor.geojson",
      "NRT2_0_Space.geojson",
      "NRT2_1_Drawing.geojson",
      "NRT2_1_Facility.geojson",
      "NRT2_1_Fixture.geojson",
      "NRT2_1_Floor.geojson",
      "NRT2_1_Opening.geojson",
      "NRT2_1_Space.geojson",
      "NRT2_2_Drawing.geojson",
      "NRT2_2_Facility.geojson",
      "NRT2_2_Fixture.geojson",
      "NRT2_2_Floor.geojson",
      "NRT2_2_Opening.geojson",
      "NRT2_2_Space.geojson",
      "NRT2_3_Drawing.geojson",
      "NRT2_3_Facility.geojson",
      "NRT2_3_Fixture.geojson",
      "NRT2_3_Floor.geojson",
      "NRT2_3_Opening.geojson",
      "NRT2_3_Space.geojson",
      "NRT2_3out_Fixture.geojson",
      "NRT2_3out_Floor.geojson",
      "NRT2_3out_Space.geojson",
      "NRT2_4_Drawing.geojson",
      "NRT2_4_Facility.geojson",
      "NRT2_4_Fixture.geojson",
      "NRT2_4_Floor.geojson",
      "NRT2_4_Opening.geojson",
      "NRT2_4_Space.geojson",
      "NRT2_4out_Drawing.geojson",
      "NRT2_4out_Facility.geojson",
      "NRT2_4out_Fixture.geojson",
      "NRT2_4out_Floor.geojson",
      "NRT2_4out_Space.geojson",
      "NRT2_B1_Facility.geojson",
      "NRT2_B1_Fixture.geojson",
      "NRT2_B1_Floor.geojson",
      "NRT2_B1_Opening.geojson",
      "NRT2_B1_Space.geojson",
      "NRT3_0_Drawing.geojson",
      "NRT3_0_Facility.geojson",
      "NRT3_0_Floor.geojson",
      "NRT3_0_Space.geojson",
      "NRT3_1_Drawing.geojson",
      "NRT3_1_Facility.geojson",
      "NRT3_1_Fixture.geojson",
      "NRT3_1_Floor.geojson",
      "NRT3_1_Opening.geojson",
      "NRT3_1_Space.geojson",
      "NRT3_2_Drawing.geojson",
      "NRT3_2_Facility.geojson",
      "NRT3_2_Fixture.geojson",
      "NRT3_2_Floor.geojson",
      "NRT3_2_Opening.geojson",
      "NRT3_2_Space.geojson",
      "Parking_NRT2_B1_Drawing.geojson",
      "Parking_NRT2_B1_Facility.geojson",
      "Parking_NRT2_B1_Fixture.geojson",
      "Parking_NRT2_B1_Floor.geojson",
      "Parking_NRT2_B1_Opening.geojson",
      "Parking_NRT2_B1_Space.geojson",
      "Parking_NRT2_B1out_Drawing.geojson",
      "Parking_NRT2_B1out_Facility.geojson",
      "Parking_NRT2_B1out_Fixture.geojson",
      "Parking_NRT2_B1out_Floor.geojson",
      "Parking_NRT2_B1out_Space.geojson",
      "Parking_NRT2_B2_Drawing.geojson",
      "Parking_NRT2_B2_Facility.geojson",
      "Parking_NRT2_B2_Fixture.geojson",
      "Parking_NRT2_B2_Floor.geojson",
      "Parking_NRT2_B2_Opening.geojson",
      "Parking_NRT2_B2_Space.geojson",
      "Railway_NRT2_B1_Facility.geojson",
      "Railway_NRT2_B1_Fixture.geojson",
      "Railway_NRT2_B1_Floor.geojson",
      "Railway_NRT2_B1_Opening.geojson",
      "Railway_NRT2_B1_Space.geojson",
      "Railway_NRT2_B1_TWSI_Line.geojson",
      "Railway_NRT2_B1_TWSI_Point.geojson",
    ],
    center: [49981.70887830284, -25506.22867806066] as [number, number],
    coordinate: {
      lat: 35.773122623636617,
      lon: 140.38708573103551,
    },
    source: {
      text: "成田国際空港屋内地図オープンデータ(令和2年度更新版)(国土交通省)",
      url: "https://www.geospatial.jp/ckan/dataset/mlit-indoor-narita-airport-r2",
    },
  },
};
