export const NissanStd = {
  NissanStd: {
    name: "横浜国際総合競技場",
    rootPath: "/NissanStd/",
    networkFile: {
      node: "NissanStd_node.geojson",
      link: "NissanStd_link.geojson",
    },
    geoFiles: [
      "NissanStd_0_Drawing.geojson",
      "NissanStd_0_Facility.geojson",
      "NissanStd_0_Floor.geojson",
      "NissanStd_0_Space.geojson",
      "NissanStd_1_Drawing.geojson",
      "NissanStd_1_Facility.geojson",
      "NissanStd_1_Floor.geojson",
      "NissanStd_1_Space.geojson",
      "NissanStd_2_Facility.geojson",
      "NissanStd_2_Floor.geojson",
      "NissanStd_2_Space.geojson",
      "NissanStd_2out_Drawing.geojson",
      "NissanStd_2out_Facility.geojson",
      "NissanStd_2out_Fixture.geojson",
      "NissanStd_2out_Floor.geojson",
      "NissanStd_2out_Space.geojson",
      "NissanStd_2out_TWSI_Line.geojson",
      "NissanStd_2out_TWSI_Point.geojson",
      "NissanStd_4_Drawing.geojson",
      "NissanStd_4_Facility.geojson",
      "NissanStd_4_Fixture.geojson",
      "NissanStd_4_Floor.geojson",
      "NissanStd_4_Opening.geojson",
      "NissanStd_4_Space.geojson",
      "NissanStd_4_TWSI_Line.geojson",
      "NissanStd_4_TWSI_Point.geojson",
      "NissanStd_4out_Drawing.geojson",
      "NissanStd_4out_Facility.geojson",
      "NissanStd_4out_Fixture.geojson",
      "NissanStd_4out_Floor.geojson",
      "NissanStd_4out_Space.geojson",
      "NissanStd_4out_TWSI_Line.geojson",
      "NissanStd_4out_TWSI_Point.geojson",
      "NissanStd_5_Drawing.geojson",
      "NissanStd_5_Facility.geojson",
      "NissanStd_5_Fixture.geojson",
      "NissanStd_5_Floor.geojson",
      "NissanStd_5_Space.geojson",
      "NissanStd_6_Drawing.geojson",
      "NissanStd_6_Facility.geojson",
      "NissanStd_6_Fixture.geojson",
      "NissanStd_6_Floor.geojson",
      "NissanStd_6_Space.geojson",
      "NissanStd_7_Drawing.geojson",
      "NissanStd_7_Facility.geojson",
      "NissanStd_7_Floor.geojson",
      "NissanStd_7_Space.geojson",
      "NissanStdSeat_4_Floor.geojson",
      "NissanStdSeat_4_Space.geojson",
      "NissanStdSeat_7_Floor.geojson",
      "NissanStdSeat_7_Space.geojson",
    ],
    center: [-20584.916804536762, -54335.17151238966] as [number, number],
    coordinate: {
      lat: 35.508893267585599,
      lon: 139.60472214430615,
    },
  },
};
