export const ShinjukuTerminal = {
  ShinjukuTerminal: {
    rootPath: "./ShinjukuTerminal/",
    networkFiles: {
      node: "Shinjuku_node.geojson",
      link: "Shinjuku_link.geojson",
    },
    terrainFiles: "ShinjukuTerminal_Terrain.geojson",
    geoFile: [
      "ShinjukuTerminal_B3_Space.geojson",
      "ShinjukuTerminal_B2_Space.geojson",
      "ShinjukuTerminal_B1_Space.geojson",
      "ShinjukuTerminal_0_Space.geojson",
      "ShinjukuTerminal_1_Space.geojson",
      "ShinjukuTerminal_2_Space.geojson",
      "ShinjukuTerminal_2out_Space.geojson",
      "ShinjukuTerminal_3_Space.geojson",
      "ShinjukuTerminal_3out_Space.geojson",
      "ShinjukuTerminal_4_Space.geojson",
      "ShinjukuTerminal_4out_Space.geojson",
      "ShinjukuTerminal_B3_Floor.geojson",
      "ShinjukuTerminal_B2_Floor.geojson",
      "ShinjukuTerminal_B1_Floor.geojson",
      "ShinjukuTerminal_0_Floor.geojson",
      "ShinjukuTerminal_1_Floor.geojson",
      "ShinjukuTerminal_2_Floor.geojson",
      "ShinjukuTerminal_2out_Floor.geojson",
      "ShinjukuTerminal_3_Floor.geojson",
      "ShinjukuTerminal_3out_Floor.geojson",
      "ShinjukuTerminal_4_Floor.geojson",
      "ShinjukuTerminal_4out_Floor.geojson",
      "ShinjukuTerminal_B3_Fixture.geojson",
      "ShinjukuTerminal_B2_Fixture.geojson",
      "ShinjukuTerminal_B1_Fixture.geojson",
      "ShinjukuTerminal_0_Fixture.geojson",
      "ShinjukuTerminal_2_Fixture.geojson",
      "ShinjukuTerminal_2out_Fixture.geojson",
      "ShinjukuTerminal_3_Fixture.geojson",
      "ShinjukuTerminal_3out_Fixture.geojson",
      "ShinjukuTerminal_4_Fixture.geojson",
      "ShinjukuTerminal_4out_Fixture.geojson",
    ],
  },
};
