export const ShinjukuTerminal = {
  ShinjukuTerminal: {
    name: "新宿駅",
    rootPath: "/ShinjukuTerminal/",
    networkFile: {
      node: "Shinjuku_node.geojson",
      link: "Shinjuku_link.geojson",
    },
    terrainFile: "ShinjukuTerminal_Terrain.geojson",
    geoFiles: [
      "ShinjukuTerminal_0_Drawing.geojson",
      "ShinjukuTerminal_0_Facility.geojson",
      "ShinjukuTerminal_0_Fixture.geojson",
      "ShinjukuTerminal_0_Floor.geojson",
      "ShinjukuTerminal_0_Space.geojson",
      "ShinjukuTerminal_0_TWSILine.geojson",
      "ShinjukuTerminal_0_TWSIPoint.geojson",
      "ShinjukuTerminal_1_Drawing.geojson",
      "ShinjukuTerminal_1_Facility.geojson",
      "ShinjukuTerminal_1_Floor.geojson",
      "ShinjukuTerminal_1_Opening.geojson",
      "ShinjukuTerminal_1_Space.geojson",
      "ShinjukuTerminal_2_Drawing.geojson",
      "ShinjukuTerminal_2_Facility.geojson",
      "ShinjukuTerminal_2_Fixture.geojson",
      "ShinjukuTerminal_2_Floor.geojson",
      "ShinjukuTerminal_2_Opening.geojson",
      "ShinjukuTerminal_2_Space.geojson",
      "ShinjukuTerminal_2out_Drawing.geojson",
      "ShinjukuTerminal_2out_Facility.geojson",
      "ShinjukuTerminal_2out_Fixture.geojson",
      "ShinjukuTerminal_2out_Floor.geojson",
      "ShinjukuTerminal_2out_Space.geojson",
      "ShinjukuTerminal_2out_TWSILine.geojson",
      "ShinjukuTerminal_2out_TWSIPoint.geojson",
      "ShinjukuTerminal_3_Drawing.geojson",
      "ShinjukuTerminal_3_Facility.geojson",
      "ShinjukuTerminal_3_Fixture.geojson",
      "ShinjukuTerminal_3_Floor.geojson",
      "ShinjukuTerminal_3_Opening.geojson",
      "ShinjukuTerminal_3_Space.geojson",
      "ShinjukuTerminal_3out_Drawing.geojson",
      "ShinjukuTerminal_3out_Facility.geojson",
      "ShinjukuTerminal_3out_Fixture.geojson",
      "ShinjukuTerminal_3out_Floor.geojson",
      "ShinjukuTerminal_3out_Space.geojson",
      "ShinjukuTerminal_4_Drawing.geojson",
      "ShinjukuTerminal_4_Facility.geojson",
      "ShinjukuTerminal_4_Fixture.geojson",
      "ShinjukuTerminal_4_Floor.geojson",
      "ShinjukuTerminal_4_Opening.geojson",
      "ShinjukuTerminal_4_Space.geojson",
      "ShinjukuTerminal_4out_Facility.geojson",
      "ShinjukuTerminal_4out_Fixture.geojson",
      "ShinjukuTerminal_4out_Floor.geojson",
      "ShinjukuTerminal_4out_Space.geojson",
      "ShinjukuTerminal_B1_Drawing.geojson",
      "ShinjukuTerminal_B1_Facility.geojson",
      "ShinjukuTerminal_B1_Fixture.geojson",
      "ShinjukuTerminal_B1_Floor.geojson",
      "ShinjukuTerminal_B1_Opening.geojson",
      "ShinjukuTerminal_B1_Space.geojson",
      "ShinjukuTerminal_B1_TWSILine.geojson",
      "ShinjukuTerminal_B1_TWSIPoint.geojson",
      "ShinjukuTerminal_B2_Drawing.geojson",
      "ShinjukuTerminal_B2_Facility.geojson",
      "ShinjukuTerminal_B2_Fixture.geojson",
      "ShinjukuTerminal_B2_Floor.geojson",
      "ShinjukuTerminal_B2_Opening.geojson",
      "ShinjukuTerminal_B2_Space.geojson",
      "ShinjukuTerminal_B2_TWSILine.geojson",
      "ShinjukuTerminal_B2_TWSIPoint.geojson",
      "ShinjukuTerminal_B3_Drawing.geojson",
      "ShinjukuTerminal_B3_Facility.geojson",
      "ShinjukuTerminal_B3_Fixture.geojson",
      "ShinjukuTerminal_B3_Floor.geojson",
      "ShinjukuTerminal_B3_Opening.geojson",
      "ShinjukuTerminal_B3_Space.geojson",
      "ShinjukuTerminal_B3_TWSILine.geojson",
      "ShinjukuTerminal_B3_TWSIPoint.geojson",
    ],
    center: [-12046.947632967798, -34285.595339754254] as [number, number],
    coordinate: {
      lat: 35.688332326154239,
      lon: 139.69877724857821,
    },
    source: {
      text: "新宿駅周辺屋内地図オープンデータ(令和2年度更新版)(国土交通省)",
      url: "https://www.geospatial.jp/ckan/dataset/mlit-indoor-shinjuku-r2",
    },
  },
};
