export const ShinyokohamaStation = {
  ShinyokohamaStation: {
    rootPath: "/ShinyokohamaStation/",
    networkFiles: {
      node: "ShinyokohamaSt_node.geojson",
      link: "ShinyokohamaSt_link.geojson",
    },
    geoFile: [
      "BLShinyoko_0_Drawing.geojson",
      "BLShinyoko_0_Facility.geojson",
      "BLShinyoko_0_Floor.geojson",
      "BLShinyoko_0_Opening.geojson",
      "BLShinyoko_0_Space.geojson",
      "BLShinyoko_B1_Drawing.geojson",
      "BLShinyoko_B1_Facility.geojson",
      "BLShinyoko_B1_Fixture.geojson",
      "BLShinyoko_B1_Floor.geojson",
      "BLShinyoko_B1_Opening.geojson",
      "BLShinyoko_B1_Space.geojson",
      "JrShinyokoSt_0_Drawing.geojson",
      "JrShinyokoSt_0_Facility.geojson",
      "JrShinyokoSt_0_Floor.geojson",
      "JrShinyokoSt_0_Opening.geojson",
      "JrShinyokoSt_0_Space.geojson",
      "JrShinyokoSt_0_TWSI_Line.geojson",
      "JrShinyokoSt_0_TWSI_Point.geojson",
      "JrShinyokoSt_1_Drawing.geojson",
      "JrShinyokoSt_1_Facility.geojson",
      "JrShinyokoSt_1_Fixture.geojson",
      "JrShinyokoSt_1_Floor.geojson",
      "JrShinyokoSt_1_Opening.geojson",
      "JrShinyokoSt_1_Space.geojson",
      "JrShinyokoSt_1_TWSI_Line.geojson",
      "JrShinyokoSt_1_TWSI_Point.geojson",
      "JrShinyokoSt_2_Drawing.geojson",
      "JrShinyokoSt_2_Facility.geojson",
      "JrShinyokoSt_2_Fixture.geojson",
      "JrShinyokoSt_2_Floor.geojson",
      "JrShinyokoSt_2_Opening.geojson",
      "JrShinyokoSt_2_Space.geojson",
      "JrShinyokoSt_2_TWSI_Line.geojson",
      "JrShinyokoSt_2_TWSI_Point.geojson",
    ],
  },
};
